# Generated by Django 3.1.7 on 2021-03-11 14:26

import diri.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('mid_name', models.CharField(max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('state', models.CharField(default='Bayelsa', max_length=255, null=True, verbose_name='State of Origin')),
                ('lga', models.CharField(default='Bayelsa', max_length=255, null=True, verbose_name='Local Government Area (LGA)')),
                ('bvn', models.CharField(default='Bayelsa', max_length=255, null=True, verbose_name='Bank Verification Number (BVN)')),
                ('bank_name', models.CharField(default='Bayelsa', max_length=255, null=True, verbose_name='Bank Name')),
                ('acc_no', models.CharField(default='Bayelsa', max_length=255, null=True, verbose_name='Account Number (NUBAN)')),
                ('st_o_acc', models.ImageField(default='Bayelsa', null=True, upload_to=diri.users.models.bank_file_path, verbose_name='Statement of Account')),
                ('acc_val', models.ImageField(default='Bayelsa', null=True, upload_to=diri.users.models.verify_file_path, verbose_name='Validate Statement')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=100, no_check_for_status=True)),
                ('entre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepreneur',
                'verbose_name_plural': 'Entrepreneurs',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
