# Generated by Django 3.1.7 on 2021-03-11 16:05

import diri.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_entrepreneurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurs',
            name='entre',
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='acc_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Account Number (NUBAN)'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='acc_val',
            field=models.ImageField(help_text='upload only clear image file', null=True, upload_to=diri.users.models.verify_file_path, verbose_name='Validate Statement'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='bank_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='bvn',
            field=models.CharField(max_length=255, null=True, verbose_name='Bank Verification Number (BVN)'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='lga',
            field=models.CharField(max_length=255, null=True, verbose_name='Local Government Area (LGA)'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='st_o_acc',
            field=models.ImageField(help_text='upload only clear image file', null=True, upload_to=diri.users.models.bank_file_path, verbose_name='Statement of Account'),
        ),
    ]
