# Generated by Django 3.1.7 on 2021-03-12 07:08

import diri.users.models
import diri.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210311_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurs',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='entrepreneurs',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='acc_val',
            field=models.ImageField(help_text='upload only clear image file', null=True, storage=diri.utils.storages.PrivateRootS3BOTO3Storage(), upload_to=diri.users.models.verify_file_path, verbose_name='Validate Statement'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='st_o_acc',
            field=models.ImageField(help_text='upload only clear image file', null=True, storage=diri.utils.storages.PrivateRootS3BOTO3Storage(), upload_to=diri.users.models.bank_file_path, verbose_name='Statement of Account'),
        ),
    ]
