# Generated by Django 3.1.7 on 2021-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210312_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurs',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7, null=True, verbose_name='Cost'),
        ),
    ]
