# Generated by Django 3.1.7 on 2021-03-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_entrepreneurs_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurs',
            name='acc_val',
        ),
    ]
