# Generated by Django 3.1.7 on 2021-03-12 12:31

import diri.users.models
import diri.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_entrepreneurs_acc_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurs',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='This is a one time payment, charged from your bank for you account validation. \n Compulsary for all applicants.', max_digits=7, null=True, verbose_name='Statement Validation Fee'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='st_o_acc',
            field=models.FileField(help_text='upload your account statement for verification', null=True, storage=diri.utils.storages.PrivateRootS3BOTO3Storage(), upload_to=diri.users.models.bank_file_path, verbose_name='Statement of Account'),
        ),
    ]
