# Generated by Django 3.1.7 on 2021-03-12 13:28

import diri.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210312_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurs',
            name='st_o_acc',
            field=models.FileField(blank=True, help_text='upload your account statement for verification', null=True, upload_to=diri.users.models.bank_file_path, verbose_name='Statement of Account'),
        ),
    ]
