# Generated by Django 3.1.7 on 2021-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210312_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurs',
            name='amount',
            field=models.CharField(default='1000.00', help_text='This is a one time payment, charged from your bank for you account validation. \n Compulsary for all applicants.', max_length=7, null=True, verbose_name='Statement Validation Fee'),
        ),
    ]
