# Generated by Django 3.1.7 on 2021-03-12 20:18

import diri.users.models
import diri.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210312_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurs',
            name='st_o_acc',
            field=models.FileField(blank=True, help_text='upload your account statement for verification', null=True, upload_to=diri.users.models.bank_file_path, validators=[diri.users.validators.validate_file_extension], verbose_name='Statement of Account'),
        ),
    ]
